name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - infra/**
      - .github/**
      - .devcontainer/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ddecontainerreg01.azurecr.io
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_SECRET }}

      - name: "Build Image"
        working-directory: ./colonysimweb
        run: |
          docker build -t ddecontainerreg01.azurecr.io/colonysimapi:${{ github.run_number }} .

      - name: "Tag Image Latest"
        working-directory: ./colonysimweb
        run: |
          docker tag ddecontainerreg01.azurecr.io/colonysimapi:${{ github.run_number }} ddecontainerreg01.azurecr.io/colonysimapi:latest

      - name: "Push"
        working-directory: ./colonysimweb
        run: |
          docker push ddecontainerreg01.azurecr.io/colonysimapi:${{ github.run_number }}
          docker push ddecontainerreg01.azurecr.io/colonysimweb:latest
